version: '3.8'
services:
  couchbase:
    image: couchbase:latest
    container_name: couchbase
    ports:
      - 8091:8091
      - 8092:8092
      - 8093:8093
      - 8094:8094
      - 11210:11210
    environment:
      COUCHBASE_ADMINISTRATOR_USERNAME: user
      COUCHBASE_ADMINISTRATOR_PASSWORD: asdf1234
      COUCHBASE_BUCKET: justdoit
      COUCHBASE_AUTO_INDEX: true
    volumes:
      - ~/couchbase/node1:/opt/couchbase/var
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8091/ui/index.html" ]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - my_network

  justdoit_server:
    build: .
    container_name: justdoit
    ports:
      - 8080:8080
    depends_on:
      couchbase:
        condition: service_healthy
    environment:
      COUCHBASE_BUCKET: justdoit
      COUCHBASE_USER: user
      COUCHBASE_PASSWORD: asdf1234
      COUCHBASE_PORT: 8091
    networks:
      - my_network

networks:
  my_network:
    driver: bridge